### ISSUE TITLE
SyntaxError: Unexpected token < in JSON at position 0

### ISSUE THREAD

**Issue by Vexyr** [KSoft-Si/ksoft.js#10]
Sometimes it throws the error in the title in reddit. What is this caused by?

**Comment by ember-ana** [comment]
This is a generic error caused when the API doesn't return a json response.  
Given your timestamp of opening the issue, I'd guess this was caused by the networking issues back then.  
Please ask questions in our Discord first for smaller stuff instead of opening an issue here :)
